# render.yaml
services:
  - type: web
    name: backend
    env: node
    region: oregon
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        value: mongodb+srv://...
      - key: JWT_SECRET
        value: sua_chave_secreta